### ISSUE TITLE
Add file checking

### ISSUE THREAD

**Issue by poproar** [BarnabasRobotics/mac-bash-ardublock#1]
https://github.com/BarnabasRobotics/mac-bash-ardublock/blob/246e862fd5e1fafb50c694a16007412ec5ff1047/ArduBlockMacInstall/ArduBlockInstallBASH#L77
I was wondering if we need something like:

```zsh
DRIVERZIP='CH34x_Install_V1.3.zip'
DRIVER='ch34x_install_v1.3.pkg'

if test -f "./$DRIVER"; then
    echo "\nRunning install"
    chmod +x $DRIVER
    open $DRIVER
    sudo installer -verboseR -allowUntrusted -pkg $DRIVER -target /
elif test -f "./$DRIVERZIP"; then
    echo "\nUnzipping Driver"
    unzip $DRIVERZIP
    chmod +x $DRIVER
    echo "\nRunning install"
    open $DRIVER
    sudo installer -verboseR -allowUntrusted -pkg $DRIVER -target /
else
    echo "CH34x files are missing. Driver not installed."
fi
```

And do we only run the restart if the driver successfully installs?

**Comment by edwardbarnabas** [comment]
This works, and also yes we only want to restart if driver installed.  Can
you add and update?

Best Regards,
Edward Li

BARNABAS ROBOTICS
Co-Founder | Chief Encourager
Phone:  626.578.5390

www.barnabasrobotics.com
www.facebook.com/barnabasrobotics
